### ISSUE TITLE
免杀后面程序

### ISSUE THREAD

**Issue by ghost** [a1phaboy/FastjsonScan#10]
![image](https://user-images.githubusercontent.com/49084918/192700822-8a20da22-d2dd-4d74-b56e-d7d8e7a04038.png)
![image](https://user-images.githubusercontent.com/49084918/192700927-54eb137c-8e5c-4962-bb44-62b922650860.png)

**Comment by timetravel-boy** [comment]
我也发现了有后门

**Comment by a1phaboy** [comment]
源代码我都开源了，不放心可自行编译。请先排除自身环境因素，谢谢
