### ISSUE TITLE
疑问：AutoType探测的原理是什么？

### ISSUE THREAD

**Issue by reloc2** [a1phaboy/FastjsonScan#17]
请问下对AutoType是否开启探测的原理是什么呀？

**Comment by a1phaboy** [comment]
对于java.net.CookiePolicy类，只有开启autoType才会允许使用，所以可以通过调用Inet4Address获取dns请求，如果autoType为off的话在检测到CookiePolicy类后执行流发生改变，所以不会触发dnslog请求。具体的执行流位置我忘了。。你可以去看看源码

**Comment by reloc2** [comment]
好的感谢。
